[package]
name = "shared_memory"
description = "A user friendly crate that allows you to share memory between processes"
version = "0.11.0"
authors = ["ElasT0ny <elast0ny00@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

#Extra fields for crates.io
readme = "README.md"
documentation = "https://docs.rs/shared_memory"
repository  = "https://github.com/elast0ny/shared_memory-rs"
keywords = ["shmem", "shared", "memory", "inter-process", "process"]
categories = ["os::unix-apis","os::windows-apis","memory-management","concurrency","asynchronous"]

exclude = [
    "ci/*",
    ".travis.yml"
]

[dependencies]
quick-error = "1.*"
cfg-if = "0.*"
rand = "0.*"

[dev-dependencies]
raw_sync = "0.*"

[target.'cfg(unix)'.dependencies]
nix = "0.*"
libc = "0.*"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.*", features = ["memoryapi", "errhandlingapi"]}
