[package]
name = "shared_memory"
description = "A user friendly crate that allows you to share memory between processes"
version = "0.1.0"
authors = ["ElasT0ny <elast0ny00@gmail.com>"]
license = "MIT OR Apache-2.0"

#Extra fields for crates.io
readme = "README.md"
documentation = "https://docs.rs/shared_memory"
repository  = "https://github.com/elast0ny/shared_memory-rs"
keywords = ["shmem", "shared", "memory", "inter-process", "process"]
categories = ["os::unix-apis","os::windows-apis","memory-management","concurrency","asynchronous"]

exclude = [
    "ci/*",
    ".travis.yml"
]

[dependencies]
cfg-if = "0.1"

[target.'cfg(unix)'.dependencies]
nix = "0.10"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "winerror", "handleapi", "fileapi", "memoryapi", "errhandlingapi", "synchapi"]}
