[workspace]
members = [
    "shared_memory_derive",
]

[package]
name = "shared_memory"
description = "A user friendly crate that allows you to share memory between processes"
version = "0.9.0"
authors = ["ElasT0ny <elast0ny00@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

#Extra fields for crates.io
readme = "README.md"
documentation = "https://docs.rs/shared_memory"
repository  = "https://github.com/elast0ny/shared_memory-rs"
keywords = ["shmem", "shared", "memory", "inter-process", "process"]
categories = ["os::unix-apis","os::windows-apis","memory-management","concurrency","asynchronous"]

exclude = [
    "ci/*",
    ".travis.yml"
]

[dev-dependencies]
enum_primitive = "0.1"

[dependencies]
quick-error = "1.2"
cfg-if = "0.1"
enum_primitive = "0.1"
log = "0.4"
theban_interval_tree = "0.7"
memrange = "0.1"
rand = "0.4"
shared_memory_derive = { path = "shared_memory_derive", version = "0.9.0" }

[target.'cfg(unix)'.dependencies]
nix = "0.10"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "winerror", "handleapi", "fileapi", "memoryapi", "errhandlingapi", "synchapi"]}
